// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_admin.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_managementsystem.cpp"
#include "EWIEGA46WW/moc_patient.cpp"
#include "EWIEGA46WW/moc_register.cpp"
